### ISSUE TITLE
Comment Section made using PHP and HTML

### ISSUE THREAD

**Issue by AryanSahoo-2003** [MohmedIkram/Hacktoberfest2022#337]
Hello! As I have seen many of my peers getting stuck at how to add comment section using php ..I want to create a sample website showing a basic comment section..
Can you assign it to me under Hactoberfest ?

**Comment by Akkichau** [comment]
Hyy bro Please assign me this project i am very excited

**Comment by sufiyanirfan3** [comment]
Hi kindly assign this issue to me
