### ISSUE TITLE
Snake Game using python

### ISSUE THREAD

**Issue by mayank-del** [MohmedIkram/Hacktoberfest2022#418]
@MohmedIkram  can I add my snake game in python under Hacktoberfest 22?

**Comment by mayank-del** [comment]
@MohmedIkram , please assign this issue to me

**Comment by Craverush12** [comment]
@MohmedIkram Hi,can i get to work on this
?

**Comment by Aly838** [comment]
Please assign this to me

**Comment by itsrishav17** [comment]
Can you please assign this issue to me? I want to work on it.

**Comment by mayank-del** [comment]
@Craverush12  and all others , you have to create your issue by your own idea, this is the rule of this hacktoberfest, you can only get this issue if i am assigned but i crossed the deadline in completing it.
