### ISSUE TITLE
Transpose Matrix in Java

### ISSUE THREAD

**Issue by Mahikagarg09** [MohmedIkram/Hacktoberfest2022#589]
Can you please assign me this issue?

**Comment by RitwikGanguly** [comment]
assign me in this project

**Comment by RitwikGanguly** [comment]
@Mahikagarg09 please review and merge the problem #602

**Comment by SagarVarshney-tech** [comment]
please assign me this issue?

**Comment by jawadkhanpk** [comment]
Hey, I have a strong profile in DSA. I can implement the transpose of a matrix more accurately and precisely. 
Please Assign me this issue so that I can make a contribution to it, Thanks.
