### ISSUE TITLE
Want to add snake game built in python

### ISSUE THREAD

**Issue by Antara25-10** [MohmedIkram/Hacktoberfest2022#604]
@MohmedIkram Kindly assign me this issue under hacktoberfest 2022

**Comment by SagarVarshney-tech** [comment]
@MohmedIkram  Kindly assign me this issue under hacktoberfest 2022

**Comment by anjaliisonii** [comment]
Please sir assign me this works I am want contribute in this issues and add my code to you. Please assign me this works. I am sure my code is help to you

**Comment by Sanket2004** [comment]
It is added in the pull request

**Comment by shaheervk786** [comment]
I know snake game pls assign me this
