### ISSUE TITLE
Linked List Questions

### ISSUE THREAD

**Issue by rahulkathuriaaa** [MohmedIkram/Hacktoberfest2022#649]
I want to add 3 Linked List Question in C++

1. Reverse a Linked List
2. Merge Two Sorted Linked List
3. Detect and remove loop in a Linked List

Kindly assign me this issue.

**Comment by Manishgupta200** [comment]
I want to add multiple function question based on on Linked list in C. assign to me

**Comment by ADRITATITIR** [comment]
Can I add how to find the middle of linked list , copy linked list to a random pointer and many more questions , please assign this issue to me

**Comment by rittik29** [comment]
can you please assign me this work
i want to contribute
