### ISSUE TITLE
Simple Calculator 

### ISSUE THREAD

**Issue by andavarapulikith** [MohmedIkram/Hacktoberfest2022#673]
I  wanted to upload a simple calculator project from front end mentor using html,css,javascript

**Comment by Manishgupta200** [comment]
Assign it to me.. Would like to add

**Comment by andavarapulikith** [comment]
I would like to add

**Comment by shaheervk786** [comment]
Can u pls assign me this

**Comment by andavarapulikith** [comment]
Yes you can

**Comment by dimple031** [comment]
Can you please assign this to me?

**Comment by prabhleenn** [comment]
please assign me this
